import express, { type Express, type RequestHandler } from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import pinoHttp from "pino-http";
import fs from "fs";
import path from "path";
import { createExpressMiddleware } from "@trpc/server/adapters/express";
import router from "./routes";
import { appRouter } from "./hayo/router";
import { authenticateRequest } from "./hayo/auth";
import { logger } from "./lib/logger";
import reverseApiRoutes from "./routes/reverse";
import fixerApiRoutes from "./hayo/fixer-api-routes";

process.on("unhandledRejection", (reason: any) => {
  console.error("[Process] Unhandled rejection:", reason?.message || reason);
});
process.on("uncaughtException", (err) => {
  console.error("[Process] Uncaught exception:", err.message);
});

const app: Express = express();

app.set("trust proxy", 1);

app.use(
  pinoHttp({
    logger,
    serializers: {
      req(req) {
        return {
          id: req.id,
          method: req.method,
          url: req.url?.split("?")[0],
        };
      },
      res(res) {
        return {
          statusCode: res.statusCode,
        };
      },
    },
  }),
);

app.use(cors({ origin: true, credentials: true }));
app.use(express.json({ limit: "600mb" }));
app.use(express.urlencoded({ limit: "600mb", extended: true }));
app.use(cookieParser() as unknown as RequestHandler);

// âââ Security Middleware âââââââââââââââââââââââââââââââââââââââââ
import { securityHeaders, apiRateLimiter } from "./hayo/services/security.js";
app.use(securityHeaders);
app.use("/api/", apiRateLimiter(120));

app.use(
  "/api/trpc",
  createExpressMiddleware({
    router: appRouter,
    createContext: async ({ req, res }) => {
      const user = await authenticateRequest(req);
      return { req, res, user };
    },
  }) as unknown as RequestHandler,
);

app.use("/api", router);

// âââ Reverse Engineer REST Routes ââââââââââââââââââââââââââââââââ
app.use("/api/reverse", reverseApiRoutes);
app.use("/api/fixer", fixerApiRoutes);

// âââ Desktop Build Download Endpoint âââââââââââââââââââââââââââââ
// Streams large ZIP files (80-150MB) generated by electron-packager
app.get("/api/builds/desktop-download/:token", async (req, res) => {
  try {
    const { desktopDownloadMap } = await import("./hayo/router.js");
    const entry = desktopDownloadMap.get(req.params.token);
    if (!entry) { res.status(404).json({ error: "Ø§ÙØ±Ø§Ø¨Ø· ØºÙØ± ØµØ§ÙØ­ Ø£Ù ÙÙØªÙÙ Ø§ÙØµÙØ§Ø­ÙØ©" }); return; }
    if (Date.now() > entry.expiresAt) {
      desktopDownloadMap.delete(req.params.token);
      res.status(410).json({ error: "Ø§ÙØªÙØª ØµÙØ§Ø­ÙØ© Ø§ÙØ±Ø§Ø¨Ø·" }); return;
    }
    if (!fs.existsSync(entry.zipPath)) { res.status(404).json({ error: "Ø§ÙÙÙÙ ØºÙØ± ÙÙØ¬ÙØ¯" }); return; }
    const stat = fs.statSync(entry.zipPath);
    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", `attachment; filename*=UTF-8''${encodeURIComponent(entry.filename)}`);
    res.setHeader("Content-Length", stat.size);
    const stream = fs.createReadStream(entry.zipPath);
    stream.pipe(res);
  } catch (err: any) {
    res.status(500).json({ error: "ÙØ´Ù Ø§ÙØªØ­ÙÙÙ" });
  }
});

// âââ Telegram Bot Setup âââââââââââââââââââââââââââââââââââââââââââ
// Bot 1: Trading signals  (TELEGRAM_BOT_TOKEN)       â @HAYO_AI_Signals_bot
// Bot 2: Bridge/AI agent  (TELEGRAM_BRIDGE_BOT_TOKEN) â @ALEPPO_CANDLES6_bot
//
// Using WEBHOOK mode â always wins over external polling instances.
// Each bot has its own unique path; Telegram POSTs updates there.

let telegramBotInstance: any        = null;
let telegramBridgeBotInstance: any  = null;

const WEBHOOK_PATH_TRADING = "/api/telegram/whook/trading";
const WEBHOOK_PATH_BRIDGE  = "/api/telegram/whook/bridge";
const WEBHOOK_PATH_TRADING_V2 = "/api/telegram/wh2/trading";
const WEBHOOK_PATH_BRIDGE_V2  = "/api/telegram/wh2/bridge";

// ââ Webhook receivers (must be registered BEFORE initTelegramBots) ââ
// Secret tokens are verified lazily once the bots are initialized.
let _tradingSecret: string | null = null;
let _bridgeSecret:  string | null = null;

app.post(WEBHOOK_PATH_TRADING, (req, res) => {
  // Verify Telegram secret token if set â reject spoofed/stale updates
  if (_tradingSecret) {
    const hdr = req.headers["x-telegram-bot-api-secret-token"] as string | undefined;
    if (hdr !== _tradingSecret) { res.sendStatus(403); return; }
  }
  res.sendStatus(200);
  if (telegramBotInstance) {
    try { telegramBotInstance.processUpdate(req.body); } catch {}
  }
});

app.post(WEBHOOK_PATH_BRIDGE, (req, res) => {
  if (_bridgeSecret) {
    const hdr = req.headers["x-telegram-bot-api-secret-token"] as string | undefined;
    if (hdr !== _bridgeSecret) { res.sendStatus(403); return; }
  }
  res.sendStatus(200);
  if (telegramBridgeBotInstance) {
    try { telegramBridgeBotInstance.processUpdate(req.body); } catch {}
  }
});

app.post(WEBHOOK_PATH_TRADING_V2, (req, res) => {
  if (_tradingSecret) {
    const hdr = req.headers["x-telegram-bot-api-secret-token"] as string | undefined;
    if (hdr !== _tradingSecret) { res.sendStatus(403); return; }
  }
  res.sendStatus(200);
  if (telegramBotInstance) {
    try { telegramBotInstance.processUpdate(req.body); } catch {}
  }
});

app.post(WEBHOOK_PATH_BRIDGE_V2, (req, res) => {
  if (_bridgeSecret) {
    const hdr = req.headers["x-telegram-bot-api-secret-token"] as string | undefined;
    if (hdr !== _bridgeSecret) { res.sendStatus(403); return; }
  }
  res.sendStatus(200);
  if (telegramBridgeBotInstance) {
    try { telegramBridgeBotInstance.processUpdate(req.body); } catch {}
  }
});

/** Derive a stable secret token from the bot token (sha256 hex, first 64 chars) */
function webhookSecret(botToken: string): string {
  const crypto = require("crypto") as typeof import("crypto");
  return crypto.createHash("sha256").update(botToken + "_hayo_secret").digest("hex").slice(0, 64);
}

const _lastRegLog = new Map<string, number>();

/** Register a webhook for one bot â retries silently on failure */
async function registerWebhook(token: string, webhookUrl: string, botLabel: string, silent = false): Promise<boolean> {
  try {
    const secret  = webhookSecret(token);
    const encoded = encodeURIComponent(webhookUrl);
    const r = await fetch(
      `https://api.telegram.org/bot${token}/setWebhook?url=${encoded}&drop_pending_updates=false&secret_token=${secret}&allowed_updates=["message","callback_query","inline_query"]`,
      { method: "POST" }
    );
    const d = await r.json() as any;
    if (d.ok) {
      if (!silent) {
        const now = Date.now();
        const last = _lastRegLog.get(botLabel) || 0;
        if (now - last > 60_000) {
          logger.info(`${botLabel} â Webhook registered â ${webhookUrl}`);
          _lastRegLog.set(botLabel, now);
        }
      }
      return true;
    } else {
      if (!silent && !d.description?.includes("Too Many Requests")) {
        logger.warn(`${botLabel} â ï¸ Webhook registration failed: ${d.description}`);
      }
      return false;
    }
  } catch (e: any) {
    return false;
  }
}

// Throttle repeated mismatch warnings â only log once per 30 seconds per bot
const _lastMismatchLog = new Map<string, number>();

/** Verify webhook is still pointing to our URL; re-register if not.
 *  Returns true if a re-registration was needed. */
async function ensureWebhook(token: string, webhookUrl: string, botLabel: string): Promise<boolean> {
  try {
    const r = await fetch(`https://api.telegram.org/bot${token}/getWebhookInfo`);
    const d = await r.json() as any;
    const current = d?.result?.url || "";
    if (current !== webhookUrl) {
      const now = Date.now();
      const last = _lastMismatchLog.get(botLabel) || 0;
      if (now - last > 30_000) {
        logger.warn(`${botLabel} â ï¸ Webhook mismatch (current: "${current.slice(0,40) || "(empty)"}") â re-registeringâ¦`);
        _lastMismatchLog.set(botLabel, now);
      }
      await registerWebhook(token, webhookUrl, botLabel);
      return true;
    }
  } catch {}
  return false;
}

async function initTelegramBots() {
  const { startTelegramBot } = await import("./telegram/bot.js");

  const tradingToken = process.env.TELEGRAM_BOT_TOKEN;
  const bridgeToken  = process.env.TELEGRAM_BRIDGE_BOT_TOKEN;

  const devDomain = process.env.REPLIT_DEV_DOMAIN;
  const replDomains = process.env.REPLIT_DOMAINS;
  const appUrl = (process.env.APP_URL || "").replace(/\/$/, "");

  let resolvedUrl = "";
  if (devDomain) {
    resolvedUrl = `https://${devDomain}`;
  } else if (replDomains) {
    const primary = replDomains.split(",")[0]?.trim();
    if (primary) resolvedUrl = `https://${primary}`;
  } else if (appUrl) {
    resolvedUrl = appUrl;
  }

  if (!resolvedUrl) {
    logger.warn("[TelegramBot] No webhook URL â bots disabled");
    return;
  }

  logger.info(`[TelegramBot] Using webhook base: ${resolvedUrl.slice(0, 60)}...`);

  const webhookTrading = `${resolvedUrl}${WEBHOOK_PATH_TRADING_V2}`;
  const webhookBridge  = `${resolvedUrl}${WEBHOOK_PATH_BRIDGE_V2}`;

  // ââ Bot 1: Trading ââââââââââââââââââââââââââââââââââââââââââââââ
  if (tradingToken) {
    try {
      _tradingSecret = webhookSecret(tradingToken);
      telegramBotInstance = startTelegramBot(webhookTrading, tradingToken, "trading");
      await registerWebhook(tradingToken, webhookTrading, "[TelegramBot-1]");
    } catch (e: any) {
      logger.error({ err: e.message }, "[TelegramBot-1] Failed to start trading bot");
    }
  } else {
    logger.warn("[TelegramBot-1] TELEGRAM_BOT_TOKEN not set â trading bot disabled");
  }

  // ââ Bot 2: Bridge âââââââââââââââââââââââââââââââââââââââââââââââ
  if (bridgeToken) {
    try {
      await new Promise(r => setTimeout(r, 1500));
      _bridgeSecret = webhookSecret(bridgeToken);
      telegramBridgeBotInstance = startTelegramBot(webhookBridge, bridgeToken, "bridge");
      await registerWebhook(bridgeToken, webhookBridge, "[TelegramBot-2]");
    } catch (e: any) {
      logger.error({ err: e.message }, "[TelegramBot-2] Failed to start bridge bot");
    }
  } else {
    logger.warn("[TelegramBot-2] TELEGRAM_BRIDGE_BOT_TOKEN not set â bridge bot disabled");
  }

  if (tradingToken || bridgeToken) {
    let watchdogRunning = false;

    setInterval(async () => {
      if (watchdogRunning) return;
      watchdogRunning = true;
      try {
        if (tradingToken) await registerWebhook(tradingToken, webhookTrading, "[TelegramBot-1]", true);
        await new Promise(r => setTimeout(r, 200));
        if (bridgeToken) await registerWebhook(bridgeToken, webhookBridge, "[TelegramBot-2]", true);
      } finally {
        watchdogRunning = false;
      }
    }, 3_000);
  }
}

// Initialize after server is ready
setTimeout(() => {
  initTelegramBots().catch((e) =>
    logger.error({ err: e.message }, "[TelegramBot] Init error")
  );
}, 3000);


// ─── Serve hayo-ai Frontend (SPA) ────────────────────────────────
const frontendPath = path.resolve(process.cwd(), "artifacts/hayo-ai/dist/public");
if (fs.existsSync(frontendPath)) {
  app.use(express.static(frontendPath));
  // SPA catch-all: serve index.html for non-API routes
  app.get("*", (req, res, next) => {
    if (req.path.startsWith("/api")) return next();
    res.sendFile(path.join(frontendPath, "index.html"));
  });
  logger.info("[Frontend] Serving hayo-ai from " + frontendPath);
} else {
  logger.warn("[Frontend] hayo-ai build not found at " + frontendPath);
}

export default app;
