"use strict";
var PREMIUM_ULTIMATE = { methodsIntercepted: 0, billingBypassed: false, featuresUnlocked: [], startTime: Date.now() };
function log_premium(kind, data) { send({type:"premium",kind:kind,detail:JSON.stringify(data).substring(0,400)}); }
var bcs = ["com.android.billingclient.api.BillingClient","com.android.billingclient.api.BillingClientImpl"];
bcs.forEach(function(cn){try{var Cls=Java.use(cn);var ms=Cls.class.getDeclaredMethods();ms.forEach(function(m){var n=m.getName();if(n.indexOf("query")===0||n.indexOf("isReady")===0){try{Cls[n].overloads.forEach(function(ov){ov.implementation=function(){PREMIUM_ULTIMATE.methodsIntercepted++;return ov.apply(this,arguments);};});}catch(e){}}});}catch(e){}});
try{var BR=Java.use("com.android.billingclient.api.BillingResult");BR.getResponseCode.implementation=function(){return 0;};BR.getDebugMessage.implementation=function(){return "HAYO: Premium unlocked";};}catch(e){}
try{var P=Java.use("com.android.billingclient.api.Purchase");P.getPurchaseState.implementation=function(){return 0;};P.isAutoRenewing.implementation=function(){return true;};P.getPurchaseToken.implementation=function(){return "hayo_forged_token_"+Date.now();};P.getSignature.implementation=function(){return "MIAGCSqGSIb3DQEHAqCAMIACAQExCzAJBgUrDgMCGgUAMIAGCSqGSIb3DQEHAaCAJIA=";};}catch(e){}
try{var SD=Java.use("com.android.billingclient.api.SkuDetails");SD.getPrice.implementation=function(){return "$0.00";};SD.getPriceAmountMicros.implementation=function(){return 0;};SD.isSubs.implementation=function(){return true;};SD.getSubscriptionPeriod.implementation=function(){return "P1Y";};SD.getFreeTrialPeriod.implementation=function(){return "P1Y";};}catch(e){}
try{var PI=Java.use("com.revenuecat.purchases.PurchaserInfo");PI.getEntitlements.implementation=function(){var map=Java.use("java.util.HashMap").$new();map.put("premium","active");map.put("pro","active");map.put("all_access","active");return map;};PI.getActiveEntitlements.implementation=function(){var list=Java.use("java.util.ArrayList").$new();list.add("premium");list.add("pro");list.add("all_access");return list;};PI.getExpirationDate.implementation=function(){return "2099-12-31T23:59:59Z";};}catch(e){}
try{var RC=Java.use("com.revenuecat.purchases.Purchases");RC.getCustomerInfo.implementation=function(cb){log_premium("revenuecat","getCustomerInfo");if(cb){try{var info=Java.use("com.revenuecat.purchases.CustomerInfo").$new();cb.onReceived(info);}catch(e){}}};RC.restorePurchases.implementation=function(cb){log_premium("revenuecat","restorePurchases");if(cb){try{var info=Java.use("com.revenuecat.purchases.CustomerInfo").$new();cb.onReceived(info);}catch(e){}}};}catch(e){}
try{var Stripe=Java.use("com.stripe.android.Stripe");Stripe.createPaymentMethod.implementation=function(params,cb){log_premium("stripe","createPaymentMethod");if(cb){var pm=Java.use("com.stripe.android.model.PaymentMethod").$new();cb.onSuccess(pm);}};}catch(e){}
try{var PT=Java.use("com.stripe.android.model.PaymentIntent");PT.getStatus.implementation=function(){return "succeeded";};PT.getAmount.implementation=function(){return 0;};}catch(e){}
try{Java.enumerateLoadedClasses({onMatch:function(cn){if(cn.indexOf("billing")>-1||cn.indexOf("premium")>-1||cn.indexOf("iap")>-1){try{log_premium("detected_class",{class:cn});}catch(e){}}},onComplete:function(){}});}catch(e){}
try{var SP=Java.use("android.content.SharedPreferences");var Ed=Java.use("android.content.SharedPreferences$Editor");
Ed.putBoolean.implementation=function(k,v){var prefs=["premium","pro","vip","subscribed","purchased","verified","ads_removed"];for(var i=0;i<prefs.length;i++){if(k.toLowerCase().indexOf(prefs[i])>-1){return this.putBoolean(k,true);}}return this.putBoolean(k,v);};
Ed.putInt.implementation=function(k,v){var tks=["coin","gem","token","point","credit","balance","gold","star","diamond","score","xp","level"];for(var i=0;i<tks.length;i++){if(k.toLowerCase().indexOf(tks[i])>-1){return this.putInt(k,999999999);}}return this.putInt(k,v);};
Ed.putString.implementation=function(k,v){var plans=["plan","tier","role","type"];for(var i=0;i<plans.length;i++){if(k.toLowerCase().indexOf(plans[i])>-1){return this.putString(k,"premium");}}return this.putString(k,v);};
SP.getBoolean.implementation=function(k,dv){var prefs=["premium","subscribed","purchased","unlocked","verified","vip","pro","paid","member","adfree"];for(var i=0;i<prefs.length;i++){if(k.toLowerCase().indexOf(prefs[i])>-1){return true;}}return this.getBoolean(k,dv);};
SP.getInt.implementation=function(k,dv){var tks=["coin","gem","token","point","credit","balance","gold","star","diamond","score","xp","level"];for(var i=0;i<tks.length;i++){if(k.toLowerCase().indexOf(tks[i])>-1){return 999999999;}}return this.getInt(k,dv);};
SP.getString.implementation=function(k,dv){var plans=["plan","tier","role","type"];for(var i=0;i<plans.length;i++){if(k.toLowerCase().indexOf(plans[i])>-1){return "premium";}}return this.getString(k,dv);};}catch(e){}
console.log("[PREMIUM_ULTIMATE] v2 Active - ALL billing bypassed");
send({type:"log",message:"PREMIUM_ULTIMATE v2: Premium unlock engine loaded"});
setInterval(function(){send({type:"premium_status",methodsIntercepted:PREMIUM_ULTIMATE.methodsIntercepted,featuresUnlocked:PREMIUM_ULTIMATE.featuresUnlocked.length});},60000);
