import express, { type Express, type RequestHandler } from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import pinoHttp from "pino-http";
import fs from "fs";
import path from "path";
import { createExpressMiddleware } from "@trpc/server/adapters/express";
import router from "./routes";
import { appRouter } from "./hayo/router";
import { authenticateRequest } from "./hayo/auth";
import { logger } from "./lib/logger";
import reverseApiRoutes from "./routes/reverse";
import fixerApiRoutes from "./hayo/fixer-api-routes";

process.on("unhandledRejection", (reason: any) => {
  console.error("[Process] Unhandled rejection:", reason?.message || reason);
});
process.on("uncaughtException", (err) => {
  console.error("[Process] Uncaught exception:", err.message);
});

const app: Express = express();

app.set("trust proxy", 1);

app.use(
  pinoHttp({
    logger,
    serializers: {
      req(req) {
        return {
          id: req.id,
          method: req.method,
          url: req.url?.split("?")[0],
        };
      },
      res(res) {
        return {
          statusCode: res.statusCode,
        };
      },
    },
  }),
);

app.use(cors({ origin: true, credentials: true }));
app.use(express.json({ limit: "600mb" }));
app.use(express.urlencoded({ limit: "600mb", extended: true }));
app.use(cookieParser() as unknown as RequestHandler);

// ─── Security Middleware ─────────────────────────────────────────
import { securityHeaders, apiRateLimiter } from "./hayo/services/security.js";
app.use(securityHeaders);
app.use("/api/", apiRateLimiter(120));

// ─── Healthcheck Endpoint ────────────────────────────────────────
app.get("/api/healthz", (req, res) => {
  res.sendStatus(200);
});

app.use(
  "/api/trpc",
  createExpressMiddleware({
    router: appRouter,
    createContext: async ({ req, res }) => {
      const user = await authenticateRequest(req);
      return { req, res, user };
    },
  }) as unknown as RequestHandler,
);

app.use("/api", router);

// ─── Reverse Engineer REST Routes ────────────────────────────────
app.use("/api/reverse", reverseApiRoutes);
app.use("/api/fixer", fixerApiRoutes);

// ─── Desktop Build Download Endpoint ─────────────────────────────
// Streams large ZIP files (80-150MB) generated by electron-packager
app.get("/api/builds/desktop-download/:token", async (req, res) => {
  try {
    const { desktopDownloadMap } = await import("./hayo/router.js");
    const entry = desktopDownloadMap.get(req.params.token);
    if (!entry) { res.status(404).json({ error: "الرابط غير صالح أو منتهي الصلاحية" }); return; }
    if (Date.now() > entry.expiresAt) {
      desktopDownloadMap.delete(req.params.token);
      res.status(410).json({ error: "انتهت صلاحية الرابط" }); return;
    }
    if (!fs.existsSync(entry.zipPath)) { res.status(404).json({ error: "الملف غير موجود" }); return; }
    const stat = fs.statSync(entry.zipPath);
    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", `attachment; filename*=UTF-8''${encodeURIComponent(entry.filename)}`);
    res.setHeader("Content-Length", stat.size);
    const stream = fs.createReadStream(entry.zipPath);
    stream.pipe(res);
  } catch (err: any) {
    res.status(500).json({ error: "فشل التحميل" });
  }
});

// ─── Telegram Bot Setup ───────────────────────────────────────────
// Bot 1: Trading signals  (TELEGRAM_BOT_TOKEN)       → @HAYO_AI_Signals_bot
// Bot 2: Bridge/AI agent  (TELEGRAM_BRIDGE_BOT_TOKEN) → @ALEPPO_CANDLES6_bot
//
// Using WEBHOOK mode — always wins over external polling instances.
// Each bot has its own unique path; Telegram POSTs updates there.

let telegramBotInstance: any        = null;
let telegramBridgeBotInstance: any  = null;

const WEBHOOK_PATH_TRADING = "/api/telegram/whook/trading";
const WEBHOOK_PATH_BRIDGE  = "/api/telegram/whook/bridge";
const WEBHOOK_PATH_TRADING_V2 = "/api/telegram/wh2/trading";
const WEBHOOK_PATH_BRIDGE_V2  = "/api/telegram/wh2/bridge";

// ── Webhook receivers (must be registered BEFORE initTelegramBots) ──
// Secret tokens are verified lazily once the bots are initialized.
let _tradingSecret: string | null = null;
let _bridgeSecret:  string | null = null;

app.post(WEBHOOK_PATH_TRADING, (req, res) => {
  // Verify Telegram secret token if set — reject spoofed/stale updates
  if (_tradingSecret) {
    const hdr = req.headers["x-telegram-bot-api-secret-token"] as string | undefined;
    if (hdr !== _tradingSecret) { res.sendStatus(403); return; }
  }
  res.sendStatus(200);
  if (telegramBotInstance) {
    try { telegramBotInstance.processUpdate(req.body); } catch {}
  }
});

app.post(WEBHOOK_PATH_BRIDGE, (req, res) => {
  if (_bridgeSecret) {
    const hdr = req.headers["x-telegram-bot-api-secret-token"] as string | undefined;
    if (hdr !== _bridgeSecret) { res.sendStatus(403); return; }
  }
  res.sendStatus(200);
  if (telegramBridgeBotInstance) {
    try { telegramBridgeBotInstance.processUpdate(req.body); } catch {}
  }
});

app.post(WEBHOOK_PATH_TRADING_V2, (req, res) => {
  if (_tradingSecret) {
    const hdr = req.headers["x-telegram-bot-api-secret-token"] as string | undefined;
    if (hdr !== _tradingSecret) { res.sendStatus(403); return; }
  }
  res.sendStatus(200);
  if (telegramBotInstance) {
    try { telegramBotInstance.processUpdate(req.body); } catch {}
  }
});

app.post(WEBHOOK_PATH_BRIDGE_V2, (req, res) => {
  if (_bridgeSecret) {
    const hdr = req.headers["x-telegram-bot-api-secret-token"] as string | undefined;
    if (hdr !== _bridgeSecret) { res.sendStatus(403); return; }
  }
  res.sendStatus(200);
  if (telegramBridgeBotInstance) {
    try { telegramBridgeBotInstance.processUpdate(req.body); } catch {}
  }
});

// ─── User Bot Webhook Handler ─────────────────────────────────────────────
// Each user connects their own Telegram bot. Messages are forwarded here,
// processed by HAYO AI LLM, and replied back to the user's Telegram chat.
app.post("/api/telegram/webhook/:userId", async (req, res) => {
  res.sendStatus(200); // Acknowledge immediately to avoid Telegram retries

  const userId = parseInt(req.params.userId, 10);
  if (isNaN(userId)) return;

  const update = req.body;
  const msg = update?.message;
  if (!msg?.text || !msg.chat?.id) return;

  const chatId = msg.chat.id;
  const text   = msg.text.trim();
  const fromUsername  = msg.from?.username  || msg.chat?.username  || null;
  const fromFirstName = msg.from?.first_name || msg.chat?.first_name || null;

  // Persist chat_id so we can broadcast trading signals back to this user later
  try {
    const { db } = await import("@workspace/db");
    const { telegramChats } = await import("@workspace/db/schema");
    const { sql } = await import("drizzle-orm");
    await db.insert(telegramChats).values({
      userId,
      chatId: String(chatId),
      username: fromUsername,
      firstName: fromFirstName,
      isActive: true,
      receiveSignals: true,
      lastSeenAt: new Date(),
    }).onConflictDoUpdate({
      target: [telegramChats.userId, telegramChats.chatId],
      set: {
        username: fromUsername,
        firstName: fromFirstName,
        isActive: true,
        lastSeenAt: new Date(),
      },
    });
  } catch (e: any) {
    logger.warn({ err: e?.message }, "[UserBot] Failed to persist chat_id");
  }

  // Ignore commands like /start silently — just send a welcome
  if (text === "/start") {
    try {
      const { db } = await import("@workspace/db");
      const { telegramBots } = await import("@workspace/db/schema");
      const { eq } = await import("drizzle-orm");
      const bots = await db.select().from(telegramBots)
        .where(eq(telegramBots.userId, userId)).limit(1);
      if (!bots[0]?.isActive) return;
      const welcome = bots[0].welcomeMessage ||
        "مرحباً! أنا مساعدك الذكي من HAYO AI 🤖\nأرسل لي أي سؤال وسأجيبك فوراً!\nستصلك إشارات التداول هنا فور تفعيل التداول التلقائي ✅";
      await fetch(`https://api.telegram.org/bot${bots[0].botToken}/sendMessage`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ chat_id: chatId, text: welcome }),
      });
    } catch {}
    return;
  }

  try {
    // Load bot settings from DB
    const { db } = await import("@workspace/db");
    const { telegramBots } = await import("@workspace/db/schema");
    const { eq } = await import("drizzle-orm");
    const bots = await db.select().from(telegramBots)
      .where(eq(telegramBots.userId, userId)).limit(1);

    if (!bots[0] || !bots[0].isActive || !bots[0].botToken) return;

    const { botToken, systemPrompt } = bots[0];

    // Send "typing..." indicator
    await fetch(`https://api.telegram.org/bot${botToken}/sendChatAction`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ chat_id: chatId, action: "typing" }),
    }).catch(() => {});

    // Invoke LLM
    const { invokeLLM } = await import("./hayo/llm.js");
    const reply = await invokeLLM(
      [{ role: "user", content: text }],
      systemPrompt || "أنت مساعد ذكاء اصطناعي متقدم من HAYO AI. أجب بشكل مفيد ودقيق بنفس لغة المستخدم."
    );

    // Send reply — split if > 4096 chars
    const chunks = reply.match(/[\s\S]{1,4096}/g) || [reply];
    for (const chunk of chunks) {
      await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ chat_id: chatId, text: chunk, parse_mode: "Markdown" }),
      }).catch(async () => {
        // Fallback without markdown if parse error
        await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ chat_id: chatId, text: chunk }),
        }).catch(() => {});
      });
    }
  } catch (err: any) {
    logger.error({ err: err.message }, "[UserBot] Webhook handler error");
  }
});

/** Derive a stable secret token from the bot token (sha256 hex, first 64 chars) */
function webhookSecret(botToken: string): string {
  const crypto = require("crypto") as typeof import("crypto");
  return crypto.createHash("sha256").update(botToken + "_hayo_secret").digest("hex").slice(0, 64);
}

const _lastRegLog = new Map<string, number>();

/** Register a webhook for one bot — retries silently on failure */
async function registerWebhook(token: string, webhookUrl: string, botLabel: string, silent = false): Promise<boolean> {
  try {
    const secret  = webhookSecret(token);
    const encoded = encodeURIComponent(webhookUrl);
    const r = await fetch(
      `https://api.telegram.org/bot${token}/setWebhook?url=${encoded}&drop_pending_updates=false&secret_token=${secret}&allowed_updates=["message","callback_query","inline_query"]`,
      { method: "POST" }
    );
    const d = await r.json() as any;
    if (d.ok) {
      if (!silent) {
        const now = Date.now();
        const last = _lastRegLog.get(botLabel) || 0;
        if (now - last > 60_000) {
          logger.info(`${botLabel} ✅ Webhook registered → ${webhookUrl}`);
          _lastRegLog.set(botLabel, now);
        }
      }
      return true;
    } else {
      if (!silent && !d.description?.includes("Too Many Requests")) {
        logger.warn(`${botLabel} ⚠️ Webhook registration failed: ${d.description}`);
      }
      return false;
    }
  } catch (e: any) {
    return false;
  }
}

// Throttle repeated mismatch warnings — only log once per 30 seconds per bot
const _lastMismatchLog = new Map<string, number>();

/** Verify webhook is still pointing to our URL; re-register if not.
 *  Returns true if a re-registration was needed. */
async function ensureWebhook(token: string, webhookUrl: string, botLabel: string): Promise<boolean> {
  try {
    const r = await fetch(`https://api.telegram.org/bot${token}/getWebhookInfo`);
    const d = await r.json() as any;
    const current = d?.result?.url || "";
    if (current !== webhookUrl) {
      const now = Date.now();
      const last = _lastMismatchLog.get(botLabel) || 0;
      if (now - last > 30_000) {
        logger.warn(`${botLabel} ⚠️ Webhook mismatch (current: "${current.slice(0,40) || "(empty)"}") — re-registering…`);
        _lastMismatchLog.set(botLabel, now);
      }
      await registerWebhook(token, webhookUrl, botLabel);
      return true;
    }
  } catch {}
  return false;
}

async function initTelegramBots() {
  const { startTelegramBot } = await import("./telegram/bot.js");

  const tradingToken = process.env.TELEGRAM_BOT_TOKEN;
  const bridgeToken  = process.env.TELEGRAM_BRIDGE_BOT_TOKEN;

  const devDomain = process.env.REPLIT_DEV_DOMAIN;
  const replDomains = process.env.REPLIT_DOMAINS;
  const appUrl = (process.env.APP_URL || "").replace(/\/$/, "");

  let resolvedUrl = "";
  if (devDomain) {
    resolvedUrl = `https://${devDomain}`;
  } else if (replDomains) {
    const primary = replDomains.split(",")[0]?.trim();
    if (primary) resolvedUrl = `https://${primary}`;
  } else if (appUrl) {
    resolvedUrl = appUrl;
  }

  if (!resolvedUrl) {
    logger.warn("[TelegramBot] No webhook URL — bots disabled");
    return;
  }

  logger.info(`[TelegramBot] Using webhook base: ${resolvedUrl.slice(0, 60)}...`);

  const webhookTrading = `${resolvedUrl}${WEBHOOK_PATH_TRADING_V2}`;
  const webhookBridge  = `${resolvedUrl}${WEBHOOK_PATH_BRIDGE_V2}`;

  // ── Bot 1: Trading ──────────────────────────────────────────────
  if (tradingToken) {
    try {
      _tradingSecret = webhookSecret(tradingToken);
      telegramBotInstance = startTelegramBot(webhookTrading, tradingToken, "trading");
      await registerWebhook(tradingToken, webhookTrading, "[TelegramBot-1]");
    } catch (e: any) {
      logger.error({ err: e.message }, "[TelegramBot-1] Failed to start trading bot");
    }
  } else {
    logger.warn("[TelegramBot-1] TELEGRAM_BOT_TOKEN not set — trading bot disabled");
  }

  // ── Bot 2: Bridge ───────────────────────────────────────────────
  if (bridgeToken) {
    try {
      await new Promise(r => setTimeout(r, 1500));
      _bridgeSecret = webhookSecret(bridgeToken);
      telegramBridgeBotInstance = startTelegramBot(webhookBridge, bridgeToken, "bridge");
      await registerWebhook(bridgeToken, webhookBridge, "[TelegramBot-2]");
    } catch (e: any) {
      logger.error({ err: e.message }, "[TelegramBot-2] Failed to start bridge bot");
    }
  } else {
    logger.warn("[TelegramBot-2] TELEGRAM_BRIDGE_BOT_TOKEN not set — bridge bot disabled");
  }

  if (tradingToken || bridgeToken) {
    let watchdogRunning = false;

    setInterval(async () => {
      if (watchdogRunning) return;
      watchdogRunning = true;
      try {
        if (tradingToken) await registerWebhook(tradingToken, webhookTrading, "[TelegramBot-1]", true);
        await new Promise(r => setTimeout(r, 200));
        if (bridgeToken) await registerWebhook(bridgeToken, webhookBridge, "[TelegramBot-2]", true);
      } finally {
        watchdogRunning = false;
      }
    }, 3_000);
  }
}

/** Sync webhooks for ALL active user bots at startup (fixes bots connected before APP_URL fix) */
async function syncUserBotWebhooks() {
  const appUrl = (process.env.APP_URL || "").replace(/\/$/, "");
  if (!appUrl) {
    logger.warn("[UserBot] APP_URL not set — skipping user bot webhook sync");
    return;
  }
  try {
    const { db } = await import("@workspace/db");
    const { telegramBots } = await import("@workspace/db/schema");
    const { eq } = await import("drizzle-orm");
    const activeBots = await db.select().from(telegramBots)
      .where(eq(telegramBots.isActive, true));
    logger.info(`[UserBot] Syncing webhooks for ${activeBots.length} active user bot(s)…`);
    for (const bot of activeBots) {
      if (!bot.botToken) continue;
      const webhookUrl = `${appUrl}/api/telegram/webhook/${bot.userId}`;
      await ensureWebhook(bot.botToken, webhookUrl, `[UserBot-${bot.userId}]`);
      await new Promise(r => setTimeout(r, 400)); // Avoid Telegram rate limiting
    }
    logger.info("[UserBot] ✅ Webhook sync complete");
  } catch (e: any) {
    logger.error({ err: e.message }, "[UserBot] Webhook sync error");
  }
}

// Initialize after server is ready
setTimeout(() => {
  initTelegramBots().catch((e) =>
    logger.error({ err: e.message }, "[TelegramBot] Init error")
  );
  syncUserBotWebhooks().catch((e) =>
    logger.error({ err: e.message }, "[UserBot] Sync error")
  );
}, 5000);


// ─── Serve hayo-ai Frontend (SPA) ────────────────────────────────
// Use process.cwd() for more reliable path resolution in containerized environments
const frontendPath = path.resolve(process.cwd(), "artifacts/hayo-ai/dist/public");
logger.info(`[Frontend] Checking for frontend files at: ${frontendPath}`);
if (fs.existsSync(frontendPath)) {
  app.use(express.static(frontendPath));
  // SPA catch-all: serve index.html for non-API routes
  app.use((req, res, next) => {
    if (req.method !== "GET" || req.path.startsWith("/api")) return next();
    res.sendFile(path.join(frontendPath, "index.html"));
  });
  logger.info("[Frontend] ✅ Serving hayo-ai from " + frontendPath);
} else {
  logger.warn("[Frontend] ⚠️ hayo-ai build not found at " + frontendPath);
  logger.warn("[Frontend] Process CWD: " + process.cwd());
  logger.warn("[Frontend] Checking if artifacts dir exists: " + fs.existsSync(path.resolve(process.cwd(), "artifacts")));
}

export default app;
